Исправление и дополнение документации загрузчика
kruzhok-team/lapki-docserver pull request #4
Opened 2024-01-24 11:50 UTC by Roundabout1

2024-01-24 15:24 UTC, chekoopa requested changes

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/01 Подключение плат Arduino.html
> +    <em>У&nbsp;удалённого сервера может стоять ограничение на&nbsp;то&nbsp;, как&nbsp;часто пользователь может запрашивать операцию Обновления.</em>
Лишний неразрывный пробел после то

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/05 Ошибки подключения к загрузчику.html
> +    При&nbsp;отсутствие соединения с&nbsp;<strong>локальным (удалённым) загрузчиком</strong>, кнопка <strong>Обновить</strong> заменяется на&nbsp;кнопку <strong>Перезапустить (Переподключиться)</stro
При отсутстви**и**

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/05 Ошибки подключения к загрузчику.html
> +    При неудачном соединении или&nbsp;потере его с&nbsp;удалённым загрузчиком IDE попытается несколько раз автоматически переподключиться (исключение: если возникла ошибка, связанная с некорректными
Неразрывный пробел после «с»

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/04 Загрузка прошивки в плату Arduino.html
> +    Если под кнопкой <strong>Загрузить</strong>, появилась надпись типа <strong>из файла file.hex</strong>, где file - это название файла, то&nbsp;значит, этот файл будет выбран для загрузки в&nbsp;у
то значит -> значит, или вообще убрать.

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/04 Загрузка прошивки в плату Arduino.html
> +    Откройте файл с прошивкой для&nbsp;<strong>Arduino</strong> (с расширением .hex) через кнопку <strong>...</strong> или&nbsp;создайте и скомпилируйте свою через IDE. Подключите к&nbsp;компьютеру п
создайте схему и скомпилируйте её 
Мы и так в IDE!

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/03 Переключение между локальным и удалённым загрузчиком.html
> +    В&nbsp;окне настроек загрузчика, написан <strong>Текущий тип сервера</strong> (<strong>Локальный</strong>, либо&nbsp;<strong>Удалённый</strong>).
Лишний неразрывный пробел после либо

2024-01-24 15:24 UTC, chekoopa commented on docs/03 Работа с загрузчиком/04 Загрузка прошивки в плату Arduino.html
> +    Если&nbsp;Вы&nbsp;открыли не&nbsp;тот&nbsp;файл, который Вам&nbsp;нужен была для&nbsp;прошивки, то&nbsp;нажмите на&nbsp;кнопку с&nbsp;иконкой <strong>X</strong> и&nbsp;выберите другую подходящую
нужен была?

подходящий файл прошивки

2024-01-25 06:29 UTC, Roundabout1 commented on docs/03 Работа с загрузчиком/04 Загрузка прошивки в плату Arduino.html
> +    Откройте файл с прошивкой для&nbsp;<strong>Arduino</strong> (с расширением .hex) через кнопку <strong>...</strong> или&nbsp;создайте и скомпилируйте свою через IDE. Подключите к&nbsp;компьютеру п
тут имеется ввиду, что можно создать и скомпилировать схему именно через Lapki IDE, либо взять прошивку из какого-нибудь другого места (напримере, можно создать и скомпилировать схему через Arduino IDE). Но, наверное, это и так понятно, так что можно убрать для простоты.

2024-01-25 08:43 UTC, chekoopa approved these changes

2024-01-25 08:43 UTC, merged