Добавлена инструкция для avrdude.
kruzhok-team/lapki-docserver pull request #8
Opened 2024-03-27 07:04 UTC by XidFanSan

Требуется после добавления данной документации по avrdude, добавить её открытие в клиенте.

2024-05-01 12:12 UTC, captaincod requested changes
Стоит прочесть замечания и отсмотреть ВСЕ тексты, сверяясь с ними. Текст пишется не для нас, разработчиков, а для пользователей, которым IDE будет новинкой, и, вероятно, они не являются программистами в третьем поколении

2024-05-01 13:29 UTC, XidFanSan commented on docs/04 Работа с загрузчиком/06 Ошибки подключения к загрузчику.html
> +    06. Ошибки подключение к&nbsp;загрузчику
Принял, исправлю)

2024-05-01 13:29 UTC, XidFanSan commented on docs/04 Работа с загрузчиком/06 Ошибки подключения к загрузчику.html
> +    При&nbsp;неудачном соединении или&nbsp;потере его&nbsp;с&nbsp;удалённым загрузчиком IDE попытается несколько раз автоматически переподключиться (исключение: если&nbsp;возникла ошибка, связанная с
Понял, скажу Ване, чтобы придумал как эти слова заменить, а то про загрузчик не я всё дополнял)

2024-05-01 17:06 UTC, chekoopa commented on docs/00 Введение/01 Начало работы.html
> +  <p class="mt-3">В&nbsp;<strong>графической области</strong> располагается открытая <mark>машина состояний</mark>, здесь&nbsp;же происходит работа с&nbsp;ней и&nbsp;её&nbsp;<mark>кодом</mark>.</p>
`поле редактирования`?

2024-05-01 17:07 UTC, chekoopa commented on docs/00 Введение/01 Начало работы.html
> +    <li class="list-group-item"><u>Настройки</u>&nbsp;— содержит <mark>настраиваемые элементы</mark> IDE, например, тема приложения, выбор хоста и&nbsp;порта для&nbsp;компилятора и&nbsp;т.д.</li>
Может, просто `адрес компилятора`?

2024-05-01 17:13 UTC, chekoopa commented on docs/01 Интерфейс среды/01 Главное меню/00 Введение.html
> +    <li class="list-group-item"><u>Главное меню</u>&nbsp;— включает в&nbsp;себя <mark>создание </mark> схем, <mark> открытие</mark> файлов, <mark>импорт</mark> схемы из&nbsp;игры «Берлога: Защита пас
Ну вот это всё – не главное меню, а боковая панель, в которой уже есть вкладка «Главное меню». Можно так. 

Или реально переименовать в что-то типа «Документ».

2024-07-15 16:12 UTC, chekoopa commented
Мержим в next для закрепления наработок

2024-07-15 16:12 UTC, merged